# Generated by Django 4.2.13 on 2024-06-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_parent_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.banner'),
        ),
    ]
