# Generated by Django 4.2.13 on 2024-06-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_banner_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.banner'),
        ),
    ]
