# Generated by Django 5.0.6 on 2024-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_slug_product_slug_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
