# Generated by Django 4.2.13 on 2024-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
