# Generated by Django 4.2.13 on 2024-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_full_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
